### ISSUE TITLE
Homebrew cask support

### ISSUE THREAD

**Issue by andrewsardone** [cdzombak/lofiapp#2]
Would ❤️ a `cask` definition so this can be tapped and installed via [homebrew-cask](https://github.com/Homebrew/homebrew-cask).

**Comment by honzajavorek** [comment]
Me too!

**Comment by cdzombak** [comment]
[The tool this app relied on, Nativefier, is no longer maintained.](https://github.com/nativefier/nativefier/issues/1577)

This app is therefore no longer maintained, and I'm archiving this repository.
