### ISSUE TITLE
The latest release seems to be corrupt (?)

### ISSUE THREAD

**Issue by philipp-heinrich** [cdzombak/lofiapp#6]
<img width="297" alt="Screenshot 2023-08-29 at 17 25 06" src="https://github.com/cdzombak/lofiapp/assets/44622670/bb5a67ca-4f95-4b0d-8ea7-331d06ce03e6">

M1 Pro -  Macbook Pro 16" with Montery 12.4

**Comment by cdzombak** [comment]
Hmm. I'm not sure what's causing this, and I'll have to dig into it…

**Comment by cdzombak** [comment]
[The tool this app relied on, Nativefier, is no longer maintained.](https://github.com/nativefier/nativefier/issues/1577)

This app is therefore no longer maintained, and I'm archiving this repository.
